### ISSUE TITLE
Error when readding N:N relationships

### ISSUE THREAD

**Issue by akaskela** [MscrmTools/MscrmTools.SolutionTableIntegrityManager#3]
My Contact table has custom 1:N, N:1, and N:N relationships. When I run option 2, my N:N relationship is being treated like a N:1 and I get an error. 

The log says: Contact / Many-to-One relationship / {relationship name} 

But that relationship and ID from the error are N:N

![image](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/assets/37714318/ecc88b1c-6daf-49c7-a520-4698fc32455c)

---
- Deployment: OnPremise (<--- that was autofilled but I'm Online) 
- DB Version: 9.2.23103.220
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65
- Tool Version: 1.2023.11.2

**Comment by MscrmTools** [comment]
Hi @akaskela 
Good catch, I think I know why. I was wondering what was the difference between solution component type 3 (Relationhip) and 10 (Entity Relationship). It seems one stands for NN and the other one for 1N. 
I will test this and fix the issue as soon as I can.

**Comment by MscrmTools** [comment]
@akaskela, can you try with this version?
[MscrmTools.SolutionTableIntegrityManager.zip](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/files/13270789/MscrmTools.SolutionTableIntegrityManager.zip)

**Comment by akaskela** [comment]
Unfortunately I'm still seeing the same thing.

**Comment by MscrmTools** [comment]
@akaskela This one should work (hopefully).

[MscrmTools.SolutionTableIntegrityManager.zip](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/files/13277625/MscrmTools.SolutionTableIntegrityManager.zip)

**Comment by akaskela** [comment]
@MscrmTools - this fixed the issue and is 100%. Thanks!

**Comment by MscrmTools** [comment]
Great! I will release this new version then
