### ISSUE TITLE
Need action to remove managed components for partial tables

### ISSUE THREAD

**Issue by akaskela** [MscrmTools/MscrmTools.SolutionTableIntegrityManager#4]
Feedback: This tool is fantastic and has saved me so much time. One action type that's missing is removing uncustomized components when you only have part of a table in the solution.

In my case, I have the Account table with some customized and some uncustomized OOB components. I want to remove the uncustomized components but the only way to do that is to remove the partial table from the solution, add the full table back in, then run the tool on the full table.

---
- Deployment: Online
- DB Version: 9.2.24024.198
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 1.2023.11.4

**Comment by akaskela** [comment]
More details: when you select a managed table that's been added to the solution in part, you only get these two options which add but don't take out the untouched OOB bits. 

![image](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/assets/37714318/5a8414fa-15c7-45b1-aaa4-799cc3256c8e)

**Comment by MscrmTools** [comment]
Great suggestion @akaskela, I will add this!

**Comment by MscrmTools** [comment]
@akaskela can you test with this version? There is a new fix to remove unchanged managed assets

[MscrmTools.SolutionTableIntegrityManager.zip](https://github.com/MscrmTools/MscrmTools.SolutionTableIntegrityManager/files/14793399/MscrmTools.SolutionTableIntegrityManager.zip)
